name: Daily Contributions

on:
  schedule:
    - cron: "0 9 * * *"  # Every day at 9:00 UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write         # Allow write permission for the repo content

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "Omar Thaljeni"
          git config --global user.email "thaljeniomar@gmail.com"

      - name: Make script executable and run it
        run: |
          chmod +x generate_contributions.sh
          ./generate_contributions.sh

      - name: Push commits
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/OmarThaljeni/activity-log.git
          git push origin master
